### ISSUE TITLE
Throws error when return form result

### ISSUE THREAD

**Issue by hsul4n** [lukasgit/flutter_contacts#105]
Using version: ^0.4.4

Get the below error when trying to save contact from native form.
```
D/FlutterView(23081): Detaching from a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@68f2867
D/AndroidRuntime(23081): Shutting down VM
E/AndroidRuntime(23081): FATAL EXCEPTION: main
E/AndroidRuntime(23081): Process: com.example.hello_world, PID: 23081
E/AndroidRuntime(23081): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=52941, result=-1, data=Intent { act=android.provider.action.QUICK_CONTACT dat=content://com.android.contacts/contacts/lookup/0r7-2A2A/7 flg=0x4000000 cmp=com.android.contacts/.quickcontact.QuickContactActivity (has extras) }} to activity {com.example.hello_world/com.example.hello_world.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(23081): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
E/AndroidRuntime(23081): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
E/AndroidRuntime(23081): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(23081): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(23081): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(23081): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
E/AndroidRuntime(23081): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(23081): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(23081): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(23081): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23081): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(23081): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(23081): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(23081): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$BaseContactsServiceDelegate.finishWithResult(ContactsServicePlugin.java:239)
E/AndroidRuntime(23081): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$BaseContactsServiceDelegate.onActivityResult(ContactsServicePlugin.java:251)
E/AndroidRuntime(23081): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:634)
E/AndroidRuntime(23081): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:367)
E/AndroidRuntime(23081): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:546)
E/AndroidRuntime(23081): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:594)
E/AndroidRuntime(23081): 	at android.app.Activity.dispatchActivityResult(Activity.java:8110)
E/AndroidRuntime(23081): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
E/AndroidRuntime(23081): 	... 11 more
I/Process (23081): Sending signal. PID: 23081 SIG: 9
Lost connection to device.
```

**Comment by lukasgit** [comment]
Fixed in PR https://github.com/lukasgit/flutter_contacts/pull/103
