### ISSUE TITLE
Not able to add contact

### ISSUE THREAD

**Issue by mayankchauhan96** [lukasgit/flutter_contacts#121]
Actually I am building a card reader application in which data is coming from the ML model and get stored in the mycontrollers function. But on using ContactsService.addContact(contact); I am getting error. Although contact is saved in the app but not in the phone's contact list.

code:

`import 'dart:async';
import 'dart:io';
import 'package:camera_app/model/ClientModel.dart';
import '../manual_database/Database.dart';
import 'home.dart';
import 'package:flutter/material.dart';
import 'package:camera_app/services/api_service.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:contacts_service/contacts_service.dart'; 

class ManualForm extends StatefulWidget {
  final String checkPrev;
  final int pkGet;
  final String imagePath;

  const ManualForm({Key key, this.checkPrev, this.pkGet, this.imagePath})
      : super(key: key);

  @override
  _FormState createState() => _FormState();
}

class _FormState extends State<ManualForm> {
  // List<CardReader> _singleContact = <CardReader>[];
  CardReader _singleContact;

  int countId = 0;
  final myController1 = TextEditingController();
  final myController2 = TextEditingController();
  final myController3 = TextEditingController();
  final myController4 = TextEditingController();
  final myController5 = TextEditingController();
  final myController6 = TextEditingController();

  @override
  void initState() {
    print("form init");
    try {
      super.initState();
      if (widget.checkPrev == 'for_edit') {
        editForSinglecontact(widget.pkGet);
      } else if (widget.checkPrev == 'from_btn') {
        listenForSinglecontact(widget.imagePath);
      }
    } catch (e) {
      print("form init end");
    }
  }

  @override
  Widget build(BuildContext context) {
    try {
      if (_singleContact == null) {
        return WillPopScope(
            onWillPop: () => Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => Home(),
                  ),
                ),
            child: new Scaffold(
              appBar: new AppBar(
                centerTitle: true,
                title: new Text("Edit the fields"),
                backgroundColor: Color(0xFF2196F3),
              ),
              body: Center(
                  child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: <Widget>[
                    SpinKitWave(
                      color: Color(0xFF000000),
                      size: 50.0,
                    ),
                    new Text(
                      "Loading...",
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 25,
                      ),
                    ),
                  ])),
            ));
      } else {
        return WillPopScope(
            onWillPop: () => Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => Home(),
                  ),
                ),
            child: Scaffold(
                appBar: AppBar(
                  title: Text('Edit Options'),
                  backgroundColor: Color(0xFF2196F3),
                ),
                body: SingleChildScrollView(
                  child: ConstrainedBox(
                    constraints: BoxConstraints(),
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: <Widget>[
                        new Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: <Widget>[
                            // Image.network(_singleContact.image, height: 150, width: 150)
                            Image.file(File(this._singleContact.image),
                                height: 200, width: 150),
                          ],
                        ),
                        TextField(
                          controller: myController1
                            ..text = this._singleContact.name,
                          decoration: const InputDecoration(
                            icon: Icon(Icons.person),
                            hintText: 'Enter name',
                            labelText: 'Name *',
                          ),
                        ),
                        TextField(
                          controller: myController2
                            ..text = this._singleContact.organization,
                          decoration: const InputDecoration(
                            icon: Icon(Icons.language),
                            hintText: 'Enter organization',
                            labelText: 'Organization *',
                          ),
                        ),
                        TextField(
                          controller: myController3
                            ..text = this._singleContact.email,
                          decoration: const InputDecoration(
                            icon: Icon(Icons.email),
                            hintText: 'Enter email',
                            labelText: 'Email *',
                          ),
                        ),
                        TextField(
                          controller: myController4
                            ..text = this._singleContact.phone,
                          decoration: const InputDecoration(
                            icon: Icon(Icons.phone),
                            hintText: 'Enter phone no.',
                            labelText: 'Phone *',
                          ),
                        ),
                        TextField(
                          controller: myController5
                            ..text = this._singleContact.website,
                          decoration: const InputDecoration(
                            icon: Icon(Icons.web),
                            hintText: 'Enter website',
                            labelText: 'Website *',
                          ),
                        ),
                        TextField(
                          controller: myController6
                            ..text = this._singleContact.address,
                          decoration: const InputDecoration(
                            icon: Icon(Icons.location_on),
                            hintText: 'Enter address',
                            labelText: 'Address *',
                          ),
                        ),
                        new RaisedButton(
                          padding: const EdgeInsets.all(8.0),
                          textColor: Colors.white,
                          color: Color(0xFF2196F3),
                          onPressed: saveData,
                          child: new Text("Save"),
                        ),
                      ],
                    ),
                  ),
                )));
      }
    } catch (e) {
      print("form show function exception");
      return WillPopScope(
          onWillPop: () => Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => Home(),
                ),
              ),
          child: Scaffold(
            appBar: AppBar(
              title: Text('Form'),
              backgroundColor: Color(0xFF2196F3),
            ),
            body: SingleChildScrollView(
              physics: const AlwaysScrollableScrollPhysics(),
            ),
          ));
    }
  }

  void editForSinglecontact(int pkSingle) async {
    try {
      final db = await database;
      var res =
          await db.query("CardReader", where: "id = ?", whereArgs: [pkSingle]);
      this.countId = pkSingle;
      setState(() => _singleContact =
          res.isNotEmpty ? CardReader.fromMap(res.first) : Null);
    } catch (e) {
      print("editForSinglecontact exxception");
    }
  }

  void listenForSinglecontact(String imagePath) async {
    try {
      final Stream<CardReader> stream = await getSingleContactNew(imagePath);
      print("form come listenForSinglecontact");
      stream.listen((CardReader contact) {
        setState(() => _singleContact = contact);
      });
    } catch (e) {
      print("Error coming form");
      print(e);
      Navigator.push(
          context,
          MaterialPageRoute(
              builder: (context) => Home(error: "Something went wrong")));
    }
  }

  Future<void> saveData() {
    try {
      print("saving");
      CardReader cardData = CardReader(
          name: myController1.text,
          organization: myController2.text,
          email: myController3.text,
          image: _singleContact.image,
          phone: myController4.text,
          website: myController5.text,
          address: myController6.text);

      Contact contact = Contact();
        print("fi");
        contact.displayName = myController1.text ; 
        contact.phones = [Item(label: "mobile", value: myController4.text)];
        // contact.emails = [Item(label: "email", value: myController3.text)];
        contact.company = myController2.text;
        print("fi2");

      ContactsService.addContact(contact);
      print("object");
        
      newCardReader(cardData);
      onLoading();
      Timer(Duration(seconds: 2), () {
        Navigator.push(
            context, MaterialPageRoute(builder: (context) => Home()));
      });

    } catch (e) {
      print("savedata exxception");
    }
  }
  
  void saveContactInPhone() {
    try {

      String displayName;

// Company
      String company;

      // Email addresses
      Iterable<Item> emails = [];

      // Phone numbers
      Iterable<Item> phones = [];

      // Post addresses
      Iterable<PostalAddress> postalAddresses = [];

      print("saving Conatct");
      

    } catch (e) {
      print(e);
    }
  }

  void onLoading() {
    try {
      showDialog(
        context: context,
        barrierDismissible: false,
        builder: (BuildContext context) {
          return Dialog(
              backgroundColor: Colors.transparent,
              child: Container(
                  width: 15.0,
                  height: 60.0,
                  color: Colors.transparent,
                  child: new Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      new Column(
                        children: [
                          SpinKitFadingCircle(
                            color: Color(0xffffa544),
                            size: 50.0,
                          ),
                        ],
                      ),
                      new Column(
                        children: [
                          Padding(
                              padding: EdgeInsets.fromLTRB(10, 10, 10, 10),
                              child: Text('Saving...',
                                  style: TextStyle(
                                    fontSize: 22,
                                    color: Colors.blue,
                                  ))),
                        ],
                      )
                    ],
                  )));
        },
      );
    } catch (e) {
      print("onLoading exxception");
    }
  }

  void newCardReader(CardReader newCardReader) async {
    try {
      final db = await database;
      var res = await db
          .query("CardReader", where: "id = ?", whereArgs: [this.countId]);
      res.isNotEmpty ? updateClient(newCardReader) : newClient(newCardReader);
    } catch (e) {
      print("newCardReader exxception");
    }
  }

  void newClient(CardReader newCardReader) async {
    try {
      final db = await database;
      this.countId = await db.insert("CardReader", newCardReader.toMap());
    } catch (e) {
      print("newClient exxception");
    }
  }

  void updateClient(CardReader newCardReader) async {
    try {
      final db = await database;
      newCardReader.id = this.countId;
      await db.update("CardReader", newCardReader.toMap(),
          where: "id = ?", whereArgs: [this.countId]);
    } catch (e) {
      print("updateClient exxception");
    }
  }

}
`
Error:

I/flutter ( 1615): form init
I/flutter ( 1615): /data/user/0/com.example.camera_app/app_flutter/2020-05-29 23:35:12.398628.png
I/flutter ( 1615): Going Image
I/flutter ( 1615): 404
I/flutter ( 1615): Image Send
I/flutter ( 1615): form come listenForSinglecontact
I/flutter ( 1615): saving
I/flutter ( 1615): fi
I/flutter ( 1615): fi2
I/flutter ( 1615): object
E/flutter ( 1615): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FormatException: Invalid envelope
E/flutter ( 1615): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:571:7)
E/flutter ( 1615): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter ( 1615): <asynchronous suspension>
E/flutter ( 1615): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 1615): #3      ContactsService.addContact (package:contacts_service/contacts_service.dart:83:16)
E/flutter ( 1615): #4      _FormState.saveData (package:camera_app/screens/form.dart:249:23)
E/flutter ( 1615): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter ( 1615): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter ( 1615): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 1615): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter ( 1615): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter ( 1615): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
E/flutter ( 1615): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter ( 1615): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter ( 1615): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter ( 1615): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter ( 1615): #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter ( 1615): #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter ( 1615): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 1615): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 1615): #19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 1615): #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 1615): #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)

**Comment by mayankchauhan96** [comment]
No solved by using:

```
Future<void> saveContactInPhone() async {
    try {

//       String displayName;

// // Company
//       String company;

//       // Email addresses
//       Iterable<Item> emails = [];

//       // Phone numbers
//       Iterable<Item> phones = [];

//       // Post addresses
//       Iterable<PostalAddress> postalAddresses = [];

      print("saving Conatct");
      PermissionStatus permission = await Permission.contacts.status;

    if (permission != PermissionStatus.granted) {
      await Permission.contacts.request();
      PermissionStatus permission = await Permission.contacts.status;

      if (permission == PermissionStatus.granted) {
      Contact newContact = new Contact();

        newContact.givenName ="Ajay";
        newContact.familyName ="abc";

          newContact.phones = [Item(label: "mobile",value: "9998887771")];

        await ContactsService.addContact(newContact);

      } 
    } 
    else {
      Contact newContact = new Contact();

        newContact.givenName ="Ajay";
        newContact.familyName ="abc";

          newContact.phones = [Item(label: "mobile",value: "9998887771")];

        await ContactsService.addContact(newContact);
    }
      print("object");      

    } catch (e) {
      print(e);
    }
  }

```
