### ISSUE TITLE
flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin.loadContactPhotoHighRes

### ISSUE THREAD

**Issue by Veargan** [lukasgit/flutter_contacts#193]
Getting following error:

java.lang.NullPointerException

flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin.loadContactPhotoHighRes

```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$4.done(AsyncTask.java:399)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetFileDescriptor android.content.ContentResolver.openAssetFileDescriptor(android.net.Uri, java.lang.String)' on a null object reference
       at android.provider.ContactsContract$Contacts.openContactPhotoInputStream(ContactsContract.java:2168)
       at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin.loadContactPhotoHighRes(ContactsServicePlugin.java:11)
       at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin.access$700(ContactsServicePlugin.java)
       at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.doInBackground(ContactsServicePlugin.java:130)
       at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.doInBackground(ContactsServicePlugin.java)
       at android.os.AsyncTask$3.call(AsyncTask.java:378)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

99% of times happens in background
Stats of reproducing (1000 users)
39% Android 10
29% Android 9
21% Android 8
11% Android 11

**Comment by Veargan** [comment]
Any updates?

**Comment by devangichhatbar** [comment]
Any update?

**Comment by Justus-M** [comment]
Having the same issue

**Comment by ardeshir-33033** [comment]
Any updates on this?
