### ISSUE TITLE
[BUG] Null safety pre-release causes a crash

### ISSUE THREAD

**Issue by GroovinChip** [lukasgit/flutter_contacts#200]
Logs:
```
E/AndroidRuntime( 8046): FATAL EXCEPTION: pool-8-thread-1
E/AndroidRuntime( 8046): Process: com.groovinchip.flutter.callmanager, PID: 8046
E/AndroidRuntime( 8046): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime( 8046): 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
E/AndroidRuntime( 8046): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime( 8046): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime( 8046): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime( 8046): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 8046): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 8046): 	at java.lang.Thread.run(Thread.java:923)
E/AndroidRuntime( 8046): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence android.content.res.Resources.getText(int)' on a null object reference
E/AndroidRuntime( 8046): 	at android.provider.ContactsContract$CommonDataKinds$Phone.getTypeLabel(ContactsContract.java:6295)
E/AndroidRuntime( 8046): 	at flutter.plugins.contactsservice.contactsservice.Item.getPhoneLabel(Item.java:42)
E/AndroidRuntime( 8046): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin.getContactsFrom(ContactsServicePlugin.java:579)
E/AndroidRuntime( 8046): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin.access$300(ContactsServicePlugin.java:55)
E/AndroidRuntime( 8046): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.doInBackground(ContactsServicePlugin.java:444)
E/AndroidRuntime( 8046): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.doInBackground(ContactsServicePlugin.java:420)
E/AndroidRuntime( 8046): 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
E/AndroidRuntime( 8046): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime( 8046): 	... 3 more
I/Process ( 8046): Sending signal. PID: 8046 SIG: 9
```

**Comment by holy-dev** [comment]
I'm not sure if it's the pre-release as I'm using the stable version still getting the error.

**Comment by lukasgit** [comment]
Try the latest build published today 0.6.0

**Comment by GroovinChip** [comment]
Everything is working well now, thank you.

**Comment by zlshames** [comment]
I am also getting this error when my Dart Isolate is spun up and tries to access contacts:

```
2021-07-02 10:05:41.473 14769-14814/com.bluebubbles.messaging E/AndroidRuntime: FATAL EXCEPTION: pool-8-thread-1
    Process: com.bluebubbles.messaging, PID: 14769
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:415)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence android.content.res.Resources.getText(int)' on a null object reference
        at android.provider.ContactsContract$CommonDataKinds$Phone.getTypeLabel(ContactsContract.java:6288)
        at flutter.plugins.contactsservice.contactsservice.Item.getPhoneLabel(Item.java:42)
        at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin.getContactsFrom(ContactsServicePlugin.java:579)
        at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin.access$300(ContactsServicePlugin.java:55)
        at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.doInBackground(ContactsServicePlugin.java:444)
        at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.doInBackground(ContactsServicePlugin.java:420)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
 ```

For reference, I am on `contacts_serivce: ^0.6.1` and `permission_handler: ^8.1.2`

**Comment by dinesh-utrade** [comment]
Hi I am getting following crash in release app

Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.CharSequence android.content.res.Resources.getText(int)' on a null object reference
android.provider.ContactsContract$CommonDataKinds$Phone.getTypeLabel (ContactsContract.java:6288)
flutter.plugins.contactsservice.contactsservice.Item.getPhoneLabel (Item.java:4)
flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin.getContactsFrom (ContactsServicePlugin.java:213)
flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin.access$300 (ContactsServicePlugin.java)
flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.doInBackground (ContactsServicePlugin.java:92)
flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.doInBackground (ContactsServicePlugin.java)
android.os.AsyncTask$3.call (AsyncTask.java:394)
