### ISSUE TITLE
Package won't work in compute or Isolate.spawn

### ISSUE THREAD

**Issue by BenQoder** [lukasgit/flutter_contacts#223]
I am trying to get contact inside an Isolate or compute function but I get this error.

Exception has occurred.
FlutterError (ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.)

I have added 
```dart
TestWidgetsFlutterBinding.ensureInitialized()
```
to main() but that didn't help.

**Comment by Fr099y** [comment]
Same issue inside Isolate.spawn(). 
Flutter version: 2.2.0 stable
Dart version: 2.13.0
contacts_service: ^0.6.1

issue :
```
E/flutter ( 6928): Null check operator used on a null value
E/flutter ( 6928): #0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:142:86)
E/flutter ( 6928): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:148:36)
E/flutter ( 6928): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:331:12)
E/flutter ( 6928): #3      ContactsService.getContacts (package:contacts_service/contacts_service.dart:24:24)
```

**Comment by Ayman220** [comment]
I'm getting the same issue here
```
Exception has occurred.
FlutterError (Binding has not yet been initialized.
The "instance" getter on the ServicesBinding binding mixin is only available once that binding has been initialized.
Typically, this is done by calling "WidgetsFlutterBinding.ensureInitialized()" or "runApp()" (the latter calls the former). Typically this call is done in the "void main()" method. The "ensureInitialized" method is idempotent; calling it multiple times is not harmful. After calling that method, the "instance" getter will return the binding.
In a test, one can call "TestWidgetsFlutterBinding.ensureInitialized()" as the first line in the test's "main()" method to initialize the binding.
If ServicesBinding is a custom binding mixin, there must also be a custom binding class, like WidgetsFlutterBinding, but that mixes in the selected binding, and that is the class that must be constructed before using the "instance" getter.)
```
Flutter v3.0.2 stable 
contact_services 0.6.3
Any workaround for this yet?
