### ISSUE TITLE
java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by sheedo** [lukasgit/flutter_contacts#250]
My team and I have been experiencing a weird crash that is caused by the contact service plugin. Here is the stack trace:

**Stack Trace**
```
E/AndroidRuntime( 4135): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=62963, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:35285 flg=0x1 }} to activity {com.digicel.selfcare.mobile/com.example.mda.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 4135):        at android.app.ActivityThread.deliverResults(ActivityThread.java:4962)
E/AndroidRuntime( 4135):        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5003)
E/AndroidRuntime( 4135):        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime( 4135):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 4135):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)       
E/AndroidRuntime( 4135):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
E/AndroidRuntime( 4135):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime( 4135):        at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 4135):        at android.app.ActivityThread.main(ActivityThread.java:7682)
E/AndroidRuntime( 4135):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4135):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime( 4135):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime( 4135): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 4135):        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
E/AndroidRuntime( 4135):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime( 4135):        at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$BaseContactsServiceDelegate.finishWithResult(ContactsServicePlugin.java:246)
E/AndroidRuntime( 4135):        at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$BaseContactsServiceDelegate.onActivityResult(ContactsServicePlugin.java:286)
```

**Steps to Reproduce**
There is a clash between the **File Picker** and **Contact Service plugin** where both plugins trigger the **onActivityResult** callback at the same time. The Contact Service plugin always submits a reply to the method channel, even if the intent was triggered by another plugin.

1. Open gallery using file picker plugin:
      var result = await FilePicker.platform.pickFiles(type: FileType.image);
2. Open contact selector using contact sercice plugin:
      final contact = await ContactsService.openDeviceContactPicker();

**Solution**
The fix was simple, just remove the **finishWithResult** call that is done at the end in the **onActivtyResult** callback for the **ContactServicePlugin** class.

  // FIXME: Only submit a reply to the method channel if the intent was meant for you. 
  // There are several other plugins that use the onActivityResult callback 
  // finishWithResult(FORM_COULD_NOT_BE_OPEN);
  return false;

**NOTE**:
The project is currently running on an older version of flutter(1.22.6) however, I notice the logic is the same for the most recent version of the Contact service plugin therefore, I think the issue may still exist in flutter 2.

Flutter 1.22.6 • channel unknown • unknown source
Framework • revision 9b2d32b605 (7 months ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

file_picker: ^2.1.7
contacts_service: ^0.4.6

**Comment by jaigahlot** [comment]
Facing the same issue. Is there any solution to this issue?
Will this solution work? https://giters.com/lukasgit/flutter_contacts/issues/250

flutter --version
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (7 months ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

**Comment by heshaShawky** [comment]
> Facing the same issue. Is there any solution to this issue? Will this solution work? https://giters.com/lukasgit/flutter_contacts/issues/250
> 
> flutter --version Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git Framework • revision f4abaa0735 (7 months ago) • 2021-07-01 12:46:11 -0700 Engine • revision 241c87ad80 Tools • Dart 2.13.4

did you have fixed this? I am facing the same problem and already installed recent flutter version and plugins
