### ISSUE TITLE
Android permissions. Crash even if permissions is granted.

### ISSUE THREAD

**Issue by akeblom** [lukasgit/flutter_contacts#44]
When trying to ```ContactsService.getContacts()``` my android app is crashing. The permission is granted as you see in the first line below.

```
I/flutter (21167): PermissionStatus.granted
E/AndroidRuntime(21167): FATAL EXCEPTION: AsyncTask #2
E/AndroidRuntime(21167): Process: com.example.phonebook, PID: 21167
E/AndroidRuntime(21167): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(21167): 	at android.os.AsyncTask$3.done(AsyncTask.java:354)
E/AndroidRuntime(21167): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(21167): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(21167): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(21167): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
E/AndroidRuntime(21167): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(21167): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(21167): 	at java.lang.Thread.run(Thread.java:764)
E/AndroidRuntime(21167): Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.contacts.ContactsProvider2 uri content://com.android.contacts/data from pid=21167, uid=11432 requires android.permission.READ_CONTACTS, or grantUriPermission()
E/AndroidRuntime(21167): 	at android.os.Parcel.createException(Parcel.java:1950)
E/AndroidRuntime(21167): 	at android.os.Parcel.readException(Parcel.java:1918)
E/AndroidRuntime(21167): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
E/AndroidRuntime(21167): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
E/AndroidRuntime(21167): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:432)
E/AndroidRuntime(21167): 	at android.content.ContentResolver.query(ContentResolver.java:847)
E/AndroidRuntime(21167): 	at android.content.ContentResolver.query(ContentResolver.java:762)
E/AndroidRuntime(21167): 	at android.content.ContentResolver.query(ContentResolver.java:720)
E/AndroidRuntime(21167): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin.getCursor(ContactsServicePlugin.java:205)
E/AndroidRuntime(21167): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin.access$200(ContactsServicePlugin.java:38)
E/AndroidRuntime(21167): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.doInBackground(ContactsServicePlugin.java:154)
E/AndroidRuntime(21167): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.doInBackground(ContactsServicePlugin.java:133)
E/AndroidRuntime(21167): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
E/AndroidRuntime(21167): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(21167): 	... 4 more
D/OSTracker(21167): OS Event: crash
```

this is the permission I set in the manifest file.

```
<uses-permission android:name="android.permission.READ_CONTACTS "/>
    <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

**Comment by danijelzolic1** [comment]
It's because of the extra whitespace after READ_CONTACTS.
`<uses-permission android:name="android.permission.READ_CONTACTS "/>`
should be:
`<uses-permission android:name="android.permission.READ_CONTACTS"/>`

**Comment by akeblom** [comment]
Ohh, you are so right about that. Hmm, that was kind of embarrassing :)

**Comment by ardeshir-33033** [comment]
I had this error too and there was not a problem with READ_CONTACTS
there was a problem with getting permission 
change target sdk
``
targetSdkVersion 22
``
and it will be fine
