### ISSUE TITLE
Failed to delete Contacts

### ISSUE THREAD

**Issue by uohziyoam** [lukasgit/flutter_contacts#5]
Add Contacts can be successfully launched. However, I found that I could not delete any contacts.

```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(, Failed to delete contact, make sure it has a valid identifier, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
<asynchronous suspension>
#2      ContactsService.deleteContact (package:contacts_service/contacts_service.dart:46:16)
#3      ContactDetailsPage.build.<anonymous closure> (package:contacts_service_example/main.dart:135:46)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
#8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
#9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
#10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
#11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
#12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
#14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#17     _rootRunUnary (dart:async/zone.dart:1136:13)
#18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#20     _invoke1 (dart:ui/hooks.dart:250:10)
#21     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
```

**Comment by lukasgit** [comment]
@uohziyoam what was the resolution to this issue?

**Comment by b-cancel** [comment]
@uohziyoam did you every fix this?
